backend:
  name: git-gateway
  branch: master

media_folder: src/images/content
public_folder: /images

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/pages Must be unique.
    label: "Projects"  # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored, relative to project root
    create: true # Allow users to create new documents in this collection
    format: 'json'
    fields:
      - {
          label: Title, 
          name: title, 
          widget: string
        }
      - {
          label: Image, 
          name: image, 
          widget: image
        }
      - {
          label: Description, 
          name: description, 
          widget: string
        }