backend:
  name: git-gateway
  branch: master

media_folder: src/images/content
public_folder: /images

collections:

  # Used in routes, e.g., /admin/collections/sections. Must be unique.
  - name: sections
    label: Sections 
    label_singular: Section
    description: the site sections / panels
    format: json
    delete: false
    create: false
    editor:
      preview: false

    files:
      - label: Intro section
        name: intro
        file: content/intro.json

        fields:
          - label: text fragments
            name: intro--text-fragment-list
            widget: list
            fields:
              - label: text fragment
                name: intro--text-fragment 
                widget: string
                 
              - label: text fragment type
                name: intro--text-fragment-type
                widget: select
                options:
                 - { label: plain, value: 1 }
                 - { label: hoverable, value: 2 }

              - label: hoverable image
                name: intro--text-hoverable-image
                widget: image
                required: false
                hint: Only select/upload an image if this fragment is hoverable. Otherwise leave blank
                pattern: 
                  - '^[0-9a-zA-Z_\-.]+(\.(jpg|png|gif))$' 
                  - Filenames can have only alphanumeric (a to z, A to Z, 0 - 9), dash and underscore. Either png, jpg or gif (Lowercase file extension)


    files:
      - label: Art projects section
        name: art-projects
        file: content/art-projects.json

        fields:
          - label: Art projects
            name: title
            widget: list
            fields:
              - label: art project name 
                name: art-project--title 
                widget: string
             
              - label: art project image 
                name: art-project--image 
                widget: image
                pattern: 
                  - '^[0-9a-zA-Z_\-.]+(\.(jpg|png|gif))$' 
                  - Filenames can have only alphanumeric (a to z, A to Z, 0 - 9), dash and underscore. Either png, jpg or gif (Lowercase file extension)

              - label: art project type
                name: art-project-type
                widget: select
                options:
                 - { label: live art, value: 1 }
                 - { label: devising + directing, value: 2 }

              - label: art project description 
                name: art-project--description 
                widget: string
