backend:
  name: git-gateway
  branch: master

media_folder: src/images/content
public_folder: /images

collections:
  - name: front-page-collection
    label: Front panel
    format: json
    description: what goes on the front page
    # allows users to create new items in the collection; defaults to false. Folders only
    create: true 
    editor:
      preview: false

    # The path to the folder where the documents are stored, relative to project root
    folder: content/front 

    fields:
      - name: front-page-paragraph

        # delete: false prevents users from deleting items in a collection; defaults to true
        delete: true
        label: Front Page
        hint: The opening paragraph at the top. Drag and drop to order. 
        widget: list

        fields:
          - label: Text type
            name: front-page--text-type
            widget: select
            options:
             - { label: plain, value: 1 }
             - { label: hoverable, value: 2 }

          - label: Text
            name: front-page--text
            widget: string

          - label: Hoverable image
            name: front-page--hoverable-image
            widget: image
            required: false
            hint: Only choose if hoverable is selected
            pattern: 
              - '^[0-9a-zA-Z_\-.]+(\.(jpg|png|gif))$' 
              - Filenames can have only alphanumeric (a to z, A to Z, 0 - 9), dash and underscore. Either png, jpg or gif (Lowercase file extension)

  # Used in routes, e.g., /admin/collections/pages. Must be unique.
  - name: projects-collection
    label: Projects 
    format: json
    delete: false

    # The path to the folder where the documents are stored, relative to project root
    files:
      - label: Art projects
        name: art-projects
        file: content/projects/art.json 
        fields:
          - label: Art projects
            name: art-projects-list
            widget: list
            fields:
              - label: project name 
                name: project-title 
                widget: string
             
              - label: project image 
                name: project-image 
                widget: image

              - label: project description 
                name: project-description 
                widget: string
